default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5

development:
  <<: *default
  database: shin

test:
  <<: *default
  database: my_rails_api_test

production:
  <<: *default
  # HerokuではDATABASE_URL環境変数が自動的に設定されるため、以下のようにします。
  url: <%= ENV['DATABASE_URL'] %>